title: GoLangGirls
description: > # this means to ignore newlines until "baseurl:"
  One day event for girls where they can explore cool things about GoLang
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2018_style/img/icon-large.png"

include: ['_2018_pages', '_2018_pages','_2019_pages', '_2019_pages', '_2025_pages', '_2025_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/girlsgolang
  - title: twitter
    url: https://twitter.com/search?q=girlsgolang

# Build settings
markdown: kramdown
permalink: pretty
